In [ ]:
#part a

In [7]:
import numpy as np
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
my_array = np.array([1,2,3,4])
my_array2 = my_array.reshape(2,2)
print(arr2)

[[1 2]
 [3 4]]


In [18]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a+b)
print(a*b)
print(np.dot(a+b,a*b))
print(np.transpose(np.dot(a+b,a*b)))

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[198 328]
 [302 504]]
[[198 302]
 [328 504]]


In [28]:
arr = np.array([3,5,-9,15,33,4,-1,-55])
g = arr[arr>5]
print("element >5",g)
n = np.where(arr<0,0,arr)
print(n)

element >5 [15 33]
[ 3  5  0 15 33  4  0  0]


In [23]:
my_array = np.array([1,2,3,4,5])
rev_array = my_array[::-1]
print(rev_array)

[5 4 3 2 1]


In [32]:
arr = np.array([11,22,33,44,55])
mean = np.mean(arr)
print(mean)
median = np.median(arr)
print(median)
sd = np.std(arr)
print(sd)

33.0
33.0
15.556349186104045


In [42]:
array = np.array([1,2,3,4,5])
np.save('array_file.npy',array)
print("array saved as 'array_file.npy'.")
load = np.load('array_file.npy')
print(load)

array saved as 'array_file.npy'.
[1 2 3 4 5]


In [45]:
array = np.array([[1,2],[3,4]])
np.savetxt("good.txt",array)
load = np.loadtxt("good.txt")
print(load)

[[1. 2.]
 [3. 4.]]


In [43]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
merge = np.hstack((a,b))
print(merge)

[[1 2 5 6]
 [3 4 7 8]]


In [54]:
import pandas as pd 
dataset = pd.read_csv(Air_passengers.csv.csv)
dataset.head()

NameError: name 'Air_passengers' is not defined

In [ ]:
total_passengers = np.sum()